package ExampleLanguage.editor;

/*Generated by MPS */

import com.mbeddr.mpsutil.multilingual.common.runtime.plugin.MultilingualResourceBundleProvider;
import java.util.ResourceBundle;
import java.util.Locale;

public class en_GBBundleClass extends MultilingualResourceBundleProvider {
  public en_GBBundleClass() {
    super("English");
  }
  public ResourceBundle getResourceBundle(Locale locale) {
    return getResourceBundleInternal(locale);
  }
}
