package ExampleLanguage.editor;

/*Generated by MPS */

import com.mbeddr.mpsutil.multilingual.common.runtime.plugin.MultilingualResourceBundleProvider;
import java.util.ResourceBundle;
import java.util.Locale;

public class nl_NLBundleClass extends MultilingualResourceBundleProvider {
  public nl_NLBundleClass() {
    super("Nederlands");
  }
  public ResourceBundle getResourceBundle(Locale locale) {
    return getResourceBundleInternal(locale);
  }
}
